// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access_api_vehicle.proto

package org.amv.access.grpc.vehicle;

public final class AccessVehicleProto {
  private AccessVehicleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_CreateVehicleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_CreateVehicleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_CreateVehicleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_CreateVehicleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030access_api_vehicle.proto\022\016amv_access_a" +
      "pi\032\025access_api_auth.proto\"\205\001\n\024CreateVehi" +
      "cleRequest\022/\n\013issuer_auth\030\001 \001(\0132\032.amv_ac" +
      "cess_api.IssuerAuth\022\014\n\004name\030\002 \001(\t\022\023\n\013des" +
      "cription\030\003 \001(\t\022\031\n\021public_key_base64\030\004 \001(" +
      "\t\"t\n\025CreateVehicleResponse\022\035\n\025vehicle_se" +
      "rial_number\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013descr" +
      "iption\030\003 \001(\t\022\031\n\021public_key_base64\030\004 \001(\t2" +
      "p\n\016VehicleService\022^\n\rcreateVehicle\022$.amv" +
      "_access_api.CreateVehicleRequest\032%.amv_a" +
      "ccess_api.CreateVehicleResponse\"\000B3\n\033org" +
      ".amv.access.grpc.vehicleB\022AccessVehicleP" +
      "rotoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.amv.access.grpc.auth.AccessAuthProto.getDescriptor(),
        }, assigner);
    internal_static_amv_access_api_CreateVehicleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_amv_access_api_CreateVehicleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_CreateVehicleRequest_descriptor,
        new java.lang.String[] { "IssuerAuth", "Name", "Description", "PublicKeyBase64", });
    internal_static_amv_access_api_CreateVehicleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_amv_access_api_CreateVehicleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_CreateVehicleResponse_descriptor,
        new java.lang.String[] { "VehicleSerialNumber", "Name", "Description", "PublicKeyBase64", });
    org.amv.access.grpc.auth.AccessAuthProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
