// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access_api_access.proto

package org.amv.access.grpc.access;

public final class AccessProto {
  private AccessProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_AccessCertificate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_AccessCertificate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_GetAccessCertificatesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_GetAccessCertificatesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_GetAccessCertificatesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_GetAccessCertificatesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_CreateAccessCertificateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_CreateAccessCertificateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_CreateAccessCertificateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_CreateAccessCertificateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_AccessCertificateSigningRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_AccessCertificateSigningRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_SignAccessCertificateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_SignAccessCertificateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_SignAccessCertificateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_SignAccessCertificateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027access_api_access.proto\022\016amv_access_ap" +
      "i\032\025access_api_auth.proto\"\205\001\n\021AccessCerti" +
      "ficate\022\n\n\002id\030\001 \001(\t\022!\n\031device_access_cert" +
      "ificate\030\002 \001(\t\022\"\n\032vehicle_access_certific" +
      "ate\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\022\017\n\007version\030\005 \001(\005" +
      "\"O\n\034GetAccessCertificatesRequest\022/\n\013devi" +
      "ce_auth\030\001 \001(\0132\032.amv_access_api.DeviceAut" +
      "h\"_\n\035GetAccessCertificatesResponse\022>\n\023ac" +
      "cess_certificates\030\001 \003(\0132!.amv_access_api" +
      ".AccessCertificate\"\335\001\n\036CreateAccessCerti" +
      "ficateRequest\022/\n\013issuer_auth\030\001 \001(\0132\032.amv" +
      "_access_api.IssuerAuth\022\016\n\006app_id\030\002 \001(\t\022\034" +
      "\n\024device_serial_number\030\003 \001(\t\022\035\n\025vehicle_" +
      "serial_number\030\004 \001(\t\022\026\n\016validity_start\030\005 " +
      "\001(\003\022\024\n\014validity_end\030\006 \001(\003\022\017\n\007version\030\007 \001" +
      "(\005\"~\n\037CreateAccessCertificateResponse\022[\n" +
      "\"access_certificate_signing_request\030\001 \001(" +
      "\0132/.amv_access_api.AccessCertificateSign" +
      "ingRequest\"t\n\037AccessCertificateSigningRe" +
      "quest\022\n\n\002id\030\001 \001(\t\022!\n\031device_access_certi" +
      "ficate\030\002 \001(\t\022\"\n\032vehicle_access_certifica" +
      "te\030\003 \001(\t\"\272\002\n\034SignAccessCertificateReques" +
      "t\022/\n\013issuer_auth\030\001 \001(\0132\032.amv_access_api." +
      "IssuerAuth\022\035\n\025access_certificate_id\030\002 \001(" +
      "\t\0223\n+vehicle_access_certificate_signatur" +
      "e_base64\030\003 \001(\t\0220\n(signed_vehicle_access_" +
      "certificate_base64\030\004 \001(\t\0222\n*device_acces" +
      "s_certificate_signature_base64\030\005 \001(\t\022/\n\'" +
      "signed_device_access_certificate_base64\030" +
      "\006 \001(\t\"^\n\035SignAccessCertificateResponse\022=" +
      "\n\022access_certificate\030\001 \001(\0132!.amv_access_" +
      "api.AccessCertificate2\375\002\n\rAccessService\022" +
      "v\n\025getAccessCertificates\022,.amv_access_ap" +
      "i.GetAccessCertificatesRequest\032-.amv_acc" +
      "ess_api.GetAccessCertificatesResponse\"\000\022" +
      "|\n\027createAccessCertificate\022..amv_access_" +
      "api.CreateAccessCertificateRequest\032/.amv" +
      "_access_api.CreateAccessCertificateRespo" +
      "nse\"\000\022v\n\025signAccessCertificate\022,.amv_acc" +
      "ess_api.SignAccessCertificateRequest\032-.a" +
      "mv_access_api.SignAccessCertificateRespo" +
      "nse\"\000B+\n\032org.amv.access.grpc.accessB\013Acc" +
      "essProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.amv.access.grpc.auth.AccessAuthProto.getDescriptor(),
        }, assigner);
    internal_static_amv_access_api_AccessCertificate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_amv_access_api_AccessCertificate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_AccessCertificate_descriptor,
        new java.lang.String[] { "Id", "DeviceAccessCertificate", "VehicleAccessCertificate", "Name", "Version", });
    internal_static_amv_access_api_GetAccessCertificatesRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_amv_access_api_GetAccessCertificatesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_GetAccessCertificatesRequest_descriptor,
        new java.lang.String[] { "DeviceAuth", });
    internal_static_amv_access_api_GetAccessCertificatesResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_amv_access_api_GetAccessCertificatesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_GetAccessCertificatesResponse_descriptor,
        new java.lang.String[] { "AccessCertificates", });
    internal_static_amv_access_api_CreateAccessCertificateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_amv_access_api_CreateAccessCertificateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_CreateAccessCertificateRequest_descriptor,
        new java.lang.String[] { "IssuerAuth", "AppId", "DeviceSerialNumber", "VehicleSerialNumber", "ValidityStart", "ValidityEnd", "Version", });
    internal_static_amv_access_api_CreateAccessCertificateResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_amv_access_api_CreateAccessCertificateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_CreateAccessCertificateResponse_descriptor,
        new java.lang.String[] { "AccessCertificateSigningRequest", });
    internal_static_amv_access_api_AccessCertificateSigningRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_amv_access_api_AccessCertificateSigningRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_AccessCertificateSigningRequest_descriptor,
        new java.lang.String[] { "Id", "DeviceAccessCertificate", "VehicleAccessCertificate", });
    internal_static_amv_access_api_SignAccessCertificateRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_amv_access_api_SignAccessCertificateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_SignAccessCertificateRequest_descriptor,
        new java.lang.String[] { "IssuerAuth", "AccessCertificateId", "VehicleAccessCertificateSignatureBase64", "SignedVehicleAccessCertificateBase64", "DeviceAccessCertificateSignatureBase64", "SignedDeviceAccessCertificateBase64", });
    internal_static_amv_access_api_SignAccessCertificateResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_amv_access_api_SignAccessCertificateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_SignAccessCertificateResponse_descriptor,
        new java.lang.String[] { "AccessCertificate", });
    org.amv.access.grpc.auth.AccessAuthProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
