// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access_api_access.proto

package org.amv.access.grpc.access;

/**
 * Protobuf type {@code amv_access_api.CreateAccessCertificateRequest}
 */
public  final class CreateAccessCertificateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:amv_access_api.CreateAccessCertificateRequest)
    CreateAccessCertificateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateAccessCertificateRequest.newBuilder() to construct.
  private CreateAccessCertificateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateAccessCertificateRequest() {
    appId_ = "";
    deviceSerialNumber_ = "";
    vehicleSerialNumber_ = "";
    validityStart_ = 0L;
    validityEnd_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateAccessCertificateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.amv.access.grpc.auth.IssuerAuth.Builder subBuilder = null;
            if (issuerAuth_ != null) {
              subBuilder = issuerAuth_.toBuilder();
            }
            issuerAuth_ = input.readMessage(org.amv.access.grpc.auth.IssuerAuth.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(issuerAuth_);
              issuerAuth_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            appId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceSerialNumber_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            vehicleSerialNumber_ = s;
            break;
          }
          case 40: {

            validityStart_ = input.readInt64();
            break;
          }
          case 48: {

            validityEnd_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.amv.access.grpc.access.AccessProto.internal_static_amv_access_api_CreateAccessCertificateRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.amv.access.grpc.access.AccessProto.internal_static_amv_access_api_CreateAccessCertificateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.amv.access.grpc.access.CreateAccessCertificateRequest.class, org.amv.access.grpc.access.CreateAccessCertificateRequest.Builder.class);
  }

  public static final int ISSUER_AUTH_FIELD_NUMBER = 1;
  private org.amv.access.grpc.auth.IssuerAuth issuerAuth_;
  /**
   * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
   */
  public boolean hasIssuerAuth() {
    return issuerAuth_ != null;
  }
  /**
   * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
   */
  public org.amv.access.grpc.auth.IssuerAuth getIssuerAuth() {
    return issuerAuth_ == null ? org.amv.access.grpc.auth.IssuerAuth.getDefaultInstance() : issuerAuth_;
  }
  /**
   * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
   */
  public org.amv.access.grpc.auth.IssuerAuthOrBuilder getIssuerAuthOrBuilder() {
    return getIssuerAuth();
  }

  public static final int APP_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object appId_;
  /**
   * <code>string app_id = 2;</code>
   */
  public java.lang.String getAppId() {
    java.lang.Object ref = appId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appId_ = s;
      return s;
    }
  }
  /**
   * <code>string app_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAppIdBytes() {
    java.lang.Object ref = appId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_SERIAL_NUMBER_FIELD_NUMBER = 3;
  private volatile java.lang.Object deviceSerialNumber_;
  /**
   * <code>string device_serial_number = 3;</code>
   */
  public java.lang.String getDeviceSerialNumber() {
    java.lang.Object ref = deviceSerialNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceSerialNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string device_serial_number = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceSerialNumberBytes() {
    java.lang.Object ref = deviceSerialNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceSerialNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VEHICLE_SERIAL_NUMBER_FIELD_NUMBER = 4;
  private volatile java.lang.Object vehicleSerialNumber_;
  /**
   * <code>string vehicle_serial_number = 4;</code>
   */
  public java.lang.String getVehicleSerialNumber() {
    java.lang.Object ref = vehicleSerialNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vehicleSerialNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string vehicle_serial_number = 4;</code>
   */
  public com.google.protobuf.ByteString
      getVehicleSerialNumberBytes() {
    java.lang.Object ref = vehicleSerialNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vehicleSerialNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALIDITY_START_FIELD_NUMBER = 5;
  private long validityStart_;
  /**
   * <code>int64 validity_start = 5;</code>
   */
  public long getValidityStart() {
    return validityStart_;
  }

  public static final int VALIDITY_END_FIELD_NUMBER = 6;
  private long validityEnd_;
  /**
   * <code>int64 validity_end = 6;</code>
   */
  public long getValidityEnd() {
    return validityEnd_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (issuerAuth_ != null) {
      output.writeMessage(1, getIssuerAuth());
    }
    if (!getAppIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appId_);
    }
    if (!getDeviceSerialNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deviceSerialNumber_);
    }
    if (!getVehicleSerialNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, vehicleSerialNumber_);
    }
    if (validityStart_ != 0L) {
      output.writeInt64(5, validityStart_);
    }
    if (validityEnd_ != 0L) {
      output.writeInt64(6, validityEnd_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (issuerAuth_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getIssuerAuth());
    }
    if (!getAppIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appId_);
    }
    if (!getDeviceSerialNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, deviceSerialNumber_);
    }
    if (!getVehicleSerialNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, vehicleSerialNumber_);
    }
    if (validityStart_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, validityStart_);
    }
    if (validityEnd_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, validityEnd_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.amv.access.grpc.access.CreateAccessCertificateRequest)) {
      return super.equals(obj);
    }
    org.amv.access.grpc.access.CreateAccessCertificateRequest other = (org.amv.access.grpc.access.CreateAccessCertificateRequest) obj;

    boolean result = true;
    result = result && (hasIssuerAuth() == other.hasIssuerAuth());
    if (hasIssuerAuth()) {
      result = result && getIssuerAuth()
          .equals(other.getIssuerAuth());
    }
    result = result && getAppId()
        .equals(other.getAppId());
    result = result && getDeviceSerialNumber()
        .equals(other.getDeviceSerialNumber());
    result = result && getVehicleSerialNumber()
        .equals(other.getVehicleSerialNumber());
    result = result && (getValidityStart()
        == other.getValidityStart());
    result = result && (getValidityEnd()
        == other.getValidityEnd());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIssuerAuth()) {
      hash = (37 * hash) + ISSUER_AUTH_FIELD_NUMBER;
      hash = (53 * hash) + getIssuerAuth().hashCode();
    }
    hash = (37 * hash) + APP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAppId().hashCode();
    hash = (37 * hash) + DEVICE_SERIAL_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceSerialNumber().hashCode();
    hash = (37 * hash) + VEHICLE_SERIAL_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getVehicleSerialNumber().hashCode();
    hash = (37 * hash) + VALIDITY_START_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getValidityStart());
    hash = (37 * hash) + VALIDITY_END_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getValidityEnd());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.amv.access.grpc.access.CreateAccessCertificateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.amv.access.grpc.access.CreateAccessCertificateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.amv.access.grpc.access.CreateAccessCertificateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.amv.access.grpc.access.CreateAccessCertificateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.amv.access.grpc.access.CreateAccessCertificateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.amv.access.grpc.access.CreateAccessCertificateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.amv.access.grpc.access.CreateAccessCertificateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.amv.access.grpc.access.CreateAccessCertificateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.amv.access.grpc.access.CreateAccessCertificateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.amv.access.grpc.access.CreateAccessCertificateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.amv.access.grpc.access.CreateAccessCertificateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.amv.access.grpc.access.CreateAccessCertificateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.amv.access.grpc.access.CreateAccessCertificateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code amv_access_api.CreateAccessCertificateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:amv_access_api.CreateAccessCertificateRequest)
      org.amv.access.grpc.access.CreateAccessCertificateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.amv.access.grpc.access.AccessProto.internal_static_amv_access_api_CreateAccessCertificateRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.amv.access.grpc.access.AccessProto.internal_static_amv_access_api_CreateAccessCertificateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.amv.access.grpc.access.CreateAccessCertificateRequest.class, org.amv.access.grpc.access.CreateAccessCertificateRequest.Builder.class);
    }

    // Construct using org.amv.access.grpc.access.CreateAccessCertificateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (issuerAuthBuilder_ == null) {
        issuerAuth_ = null;
      } else {
        issuerAuth_ = null;
        issuerAuthBuilder_ = null;
      }
      appId_ = "";

      deviceSerialNumber_ = "";

      vehicleSerialNumber_ = "";

      validityStart_ = 0L;

      validityEnd_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.amv.access.grpc.access.AccessProto.internal_static_amv_access_api_CreateAccessCertificateRequest_descriptor;
    }

    public org.amv.access.grpc.access.CreateAccessCertificateRequest getDefaultInstanceForType() {
      return org.amv.access.grpc.access.CreateAccessCertificateRequest.getDefaultInstance();
    }

    public org.amv.access.grpc.access.CreateAccessCertificateRequest build() {
      org.amv.access.grpc.access.CreateAccessCertificateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.amv.access.grpc.access.CreateAccessCertificateRequest buildPartial() {
      org.amv.access.grpc.access.CreateAccessCertificateRequest result = new org.amv.access.grpc.access.CreateAccessCertificateRequest(this);
      if (issuerAuthBuilder_ == null) {
        result.issuerAuth_ = issuerAuth_;
      } else {
        result.issuerAuth_ = issuerAuthBuilder_.build();
      }
      result.appId_ = appId_;
      result.deviceSerialNumber_ = deviceSerialNumber_;
      result.vehicleSerialNumber_ = vehicleSerialNumber_;
      result.validityStart_ = validityStart_;
      result.validityEnd_ = validityEnd_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.amv.access.grpc.access.CreateAccessCertificateRequest) {
        return mergeFrom((org.amv.access.grpc.access.CreateAccessCertificateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.amv.access.grpc.access.CreateAccessCertificateRequest other) {
      if (other == org.amv.access.grpc.access.CreateAccessCertificateRequest.getDefaultInstance()) return this;
      if (other.hasIssuerAuth()) {
        mergeIssuerAuth(other.getIssuerAuth());
      }
      if (!other.getAppId().isEmpty()) {
        appId_ = other.appId_;
        onChanged();
      }
      if (!other.getDeviceSerialNumber().isEmpty()) {
        deviceSerialNumber_ = other.deviceSerialNumber_;
        onChanged();
      }
      if (!other.getVehicleSerialNumber().isEmpty()) {
        vehicleSerialNumber_ = other.vehicleSerialNumber_;
        onChanged();
      }
      if (other.getValidityStart() != 0L) {
        setValidityStart(other.getValidityStart());
      }
      if (other.getValidityEnd() != 0L) {
        setValidityEnd(other.getValidityEnd());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.amv.access.grpc.access.CreateAccessCertificateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.amv.access.grpc.access.CreateAccessCertificateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.amv.access.grpc.auth.IssuerAuth issuerAuth_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.amv.access.grpc.auth.IssuerAuth, org.amv.access.grpc.auth.IssuerAuth.Builder, org.amv.access.grpc.auth.IssuerAuthOrBuilder> issuerAuthBuilder_;
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public boolean hasIssuerAuth() {
      return issuerAuthBuilder_ != null || issuerAuth_ != null;
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public org.amv.access.grpc.auth.IssuerAuth getIssuerAuth() {
      if (issuerAuthBuilder_ == null) {
        return issuerAuth_ == null ? org.amv.access.grpc.auth.IssuerAuth.getDefaultInstance() : issuerAuth_;
      } else {
        return issuerAuthBuilder_.getMessage();
      }
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public Builder setIssuerAuth(org.amv.access.grpc.auth.IssuerAuth value) {
      if (issuerAuthBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        issuerAuth_ = value;
        onChanged();
      } else {
        issuerAuthBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public Builder setIssuerAuth(
        org.amv.access.grpc.auth.IssuerAuth.Builder builderForValue) {
      if (issuerAuthBuilder_ == null) {
        issuerAuth_ = builderForValue.build();
        onChanged();
      } else {
        issuerAuthBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public Builder mergeIssuerAuth(org.amv.access.grpc.auth.IssuerAuth value) {
      if (issuerAuthBuilder_ == null) {
        if (issuerAuth_ != null) {
          issuerAuth_ =
            org.amv.access.grpc.auth.IssuerAuth.newBuilder(issuerAuth_).mergeFrom(value).buildPartial();
        } else {
          issuerAuth_ = value;
        }
        onChanged();
      } else {
        issuerAuthBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public Builder clearIssuerAuth() {
      if (issuerAuthBuilder_ == null) {
        issuerAuth_ = null;
        onChanged();
      } else {
        issuerAuth_ = null;
        issuerAuthBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public org.amv.access.grpc.auth.IssuerAuth.Builder getIssuerAuthBuilder() {
      
      onChanged();
      return getIssuerAuthFieldBuilder().getBuilder();
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public org.amv.access.grpc.auth.IssuerAuthOrBuilder getIssuerAuthOrBuilder() {
      if (issuerAuthBuilder_ != null) {
        return issuerAuthBuilder_.getMessageOrBuilder();
      } else {
        return issuerAuth_ == null ?
            org.amv.access.grpc.auth.IssuerAuth.getDefaultInstance() : issuerAuth_;
      }
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.amv.access.grpc.auth.IssuerAuth, org.amv.access.grpc.auth.IssuerAuth.Builder, org.amv.access.grpc.auth.IssuerAuthOrBuilder> 
        getIssuerAuthFieldBuilder() {
      if (issuerAuthBuilder_ == null) {
        issuerAuthBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.amv.access.grpc.auth.IssuerAuth, org.amv.access.grpc.auth.IssuerAuth.Builder, org.amv.access.grpc.auth.IssuerAuthOrBuilder>(
                getIssuerAuth(),
                getParentForChildren(),
                isClean());
        issuerAuth_ = null;
      }
      return issuerAuthBuilder_;
    }

    private java.lang.Object appId_ = "";
    /**
     * <code>string app_id = 2;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string app_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string app_id = 2;</code>
     */
    public Builder setAppId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string app_id = 2;</code>
     */
    public Builder clearAppId() {
      
      appId_ = getDefaultInstance().getAppId();
      onChanged();
      return this;
    }
    /**
     * <code>string app_id = 2;</code>
     */
    public Builder setAppIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceSerialNumber_ = "";
    /**
     * <code>string device_serial_number = 3;</code>
     */
    public java.lang.String getDeviceSerialNumber() {
      java.lang.Object ref = deviceSerialNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceSerialNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string device_serial_number = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceSerialNumberBytes() {
      java.lang.Object ref = deviceSerialNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceSerialNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string device_serial_number = 3;</code>
     */
    public Builder setDeviceSerialNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceSerialNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string device_serial_number = 3;</code>
     */
    public Builder clearDeviceSerialNumber() {
      
      deviceSerialNumber_ = getDefaultInstance().getDeviceSerialNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string device_serial_number = 3;</code>
     */
    public Builder setDeviceSerialNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceSerialNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object vehicleSerialNumber_ = "";
    /**
     * <code>string vehicle_serial_number = 4;</code>
     */
    public java.lang.String getVehicleSerialNumber() {
      java.lang.Object ref = vehicleSerialNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vehicleSerialNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vehicle_serial_number = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVehicleSerialNumberBytes() {
      java.lang.Object ref = vehicleSerialNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vehicleSerialNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vehicle_serial_number = 4;</code>
     */
    public Builder setVehicleSerialNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vehicleSerialNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string vehicle_serial_number = 4;</code>
     */
    public Builder clearVehicleSerialNumber() {
      
      vehicleSerialNumber_ = getDefaultInstance().getVehicleSerialNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string vehicle_serial_number = 4;</code>
     */
    public Builder setVehicleSerialNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vehicleSerialNumber_ = value;
      onChanged();
      return this;
    }

    private long validityStart_ ;
    /**
     * <code>int64 validity_start = 5;</code>
     */
    public long getValidityStart() {
      return validityStart_;
    }
    /**
     * <code>int64 validity_start = 5;</code>
     */
    public Builder setValidityStart(long value) {
      
      validityStart_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 validity_start = 5;</code>
     */
    public Builder clearValidityStart() {
      
      validityStart_ = 0L;
      onChanged();
      return this;
    }

    private long validityEnd_ ;
    /**
     * <code>int64 validity_end = 6;</code>
     */
    public long getValidityEnd() {
      return validityEnd_;
    }
    /**
     * <code>int64 validity_end = 6;</code>
     */
    public Builder setValidityEnd(long value) {
      
      validityEnd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 validity_end = 6;</code>
     */
    public Builder clearValidityEnd() {
      
      validityEnd_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:amv_access_api.CreateAccessCertificateRequest)
  }

  // @@protoc_insertion_point(class_scope:amv_access_api.CreateAccessCertificateRequest)
  private static final org.amv.access.grpc.access.CreateAccessCertificateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.amv.access.grpc.access.CreateAccessCertificateRequest();
  }

  public static org.amv.access.grpc.access.CreateAccessCertificateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateAccessCertificateRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateAccessCertificateRequest>() {
    public CreateAccessCertificateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateAccessCertificateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateAccessCertificateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateAccessCertificateRequest> getParserForType() {
    return PARSER;
  }

  public org.amv.access.grpc.access.CreateAccessCertificateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

