// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access_api_access.proto

package org.amv.access.grpc.access;

public interface CreateAccessCertificateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amv_access_api.CreateAccessCertificateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.amv_access_api.AccessCertificateSigningRequest access_certificate_signing_request = 1;</code>
   */
  boolean hasAccessCertificateSigningRequest();
  /**
   * <code>.amv_access_api.AccessCertificateSigningRequest access_certificate_signing_request = 1;</code>
   */
  org.amv.access.grpc.access.AccessCertificateSigningRequest getAccessCertificateSigningRequest();
  /**
   * <code>.amv_access_api.AccessCertificateSigningRequest access_certificate_signing_request = 1;</code>
   */
  org.amv.access.grpc.access.AccessCertificateSigningRequestOrBuilder getAccessCertificateSigningRequestOrBuilder();
}
