// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access_api_access.proto

package org.amv.access.grpc.access;

public interface GetAccessCertificatesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amv_access_api.GetAccessCertificatesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .amv_access_api.AccessCertificate access_certificates = 1;</code>
   */
  java.util.List<org.amv.access.grpc.access.AccessCertificate> 
      getAccessCertificatesList();
  /**
   * <code>repeated .amv_access_api.AccessCertificate access_certificates = 1;</code>
   */
  org.amv.access.grpc.access.AccessCertificate getAccessCertificates(int index);
  /**
   * <code>repeated .amv_access_api.AccessCertificate access_certificates = 1;</code>
   */
  int getAccessCertificatesCount();
  /**
   * <code>repeated .amv_access_api.AccessCertificate access_certificates = 1;</code>
   */
  java.util.List<? extends org.amv.access.grpc.access.AccessCertificateOrBuilder> 
      getAccessCertificatesOrBuilderList();
  /**
   * <code>repeated .amv_access_api.AccessCertificate access_certificates = 1;</code>
   */
  org.amv.access.grpc.access.AccessCertificateOrBuilder getAccessCertificatesOrBuilder(
      int index);
}
