// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access_api_device.proto

package org.amv.access.grpc.device;

public interface CreateDeviceCertificateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amv_access_api.CreateDeviceCertificateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_public_key = 1;</code>
   */
  java.lang.String getDevicePublicKey();
  /**
   * <code>string device_public_key = 1;</code>
   */
  com.google.protobuf.ByteString
      getDevicePublicKeyBytes();
}
