// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access_api_device.proto

package org.amv.access.grpc.device;

public interface DeviceCertificateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amv_access_api.DeviceCertificateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
   */
  boolean hasDeviceCertificate();
  /**
   * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
   */
  org.amv.access.grpc.device.DeviceCertificate getDeviceCertificate();
  /**
   * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
   */
  org.amv.access.grpc.device.DeviceCertificateOrBuilder getDeviceCertificateOrBuilder();
}
