/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.amv_access_api.DeviceAuth', null, global);
goog.exportSymbol('proto.amv_access_api.IssuerAuth', null, global);
goog.exportSymbol('proto.amv_access_api.NonceAuth', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.amv_access_api.NonceAuth = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.amv_access_api.NonceAuth, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.amv_access_api.NonceAuth.displayName = 'proto.amv_access_api.NonceAuth';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.amv_access_api.NonceAuth.prototype.toObject = function(opt_includeInstance) {
  return proto.amv_access_api.NonceAuth.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.amv_access_api.NonceAuth} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.NonceAuth.toObject = function(includeInstance, msg) {
  var f, obj = {
    nonce: jspb.Message.getFieldWithDefault(msg, 1, ""),
    nonceSignature: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.amv_access_api.NonceAuth}
 */
proto.amv_access_api.NonceAuth.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.amv_access_api.NonceAuth;
  return proto.amv_access_api.NonceAuth.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.amv_access_api.NonceAuth} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.amv_access_api.NonceAuth}
 */
proto.amv_access_api.NonceAuth.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNonce(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNonceSignature(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.amv_access_api.NonceAuth.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.amv_access_api.NonceAuth.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.amv_access_api.NonceAuth} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.NonceAuth.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNonce();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNonceSignature();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string nonce = 1;
 * @return {string}
 */
proto.amv_access_api.NonceAuth.prototype.getNonce = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.amv_access_api.NonceAuth.prototype.setNonce = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string nonce_signature = 2;
 * @return {string}
 */
proto.amv_access_api.NonceAuth.prototype.getNonceSignature = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.amv_access_api.NonceAuth.prototype.setNonceSignature = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.amv_access_api.IssuerAuth = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.amv_access_api.IssuerAuth, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.amv_access_api.IssuerAuth.displayName = 'proto.amv_access_api.IssuerAuth';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.amv_access_api.IssuerAuth.prototype.toObject = function(opt_includeInstance) {
  return proto.amv_access_api.IssuerAuth.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.amv_access_api.IssuerAuth} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.IssuerAuth.toObject = function(includeInstance, msg) {
  var f, obj = {
    nonceAuth: (f = msg.getNonceAuth()) && proto.amv_access_api.NonceAuth.toObject(includeInstance, f),
    issuerUuid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.amv_access_api.IssuerAuth}
 */
proto.amv_access_api.IssuerAuth.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.amv_access_api.IssuerAuth;
  return proto.amv_access_api.IssuerAuth.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.amv_access_api.IssuerAuth} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.amv_access_api.IssuerAuth}
 */
proto.amv_access_api.IssuerAuth.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.amv_access_api.NonceAuth;
      reader.readMessage(value,proto.amv_access_api.NonceAuth.deserializeBinaryFromReader);
      msg.setNonceAuth(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIssuerUuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.amv_access_api.IssuerAuth.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.amv_access_api.IssuerAuth.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.amv_access_api.IssuerAuth} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.IssuerAuth.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNonceAuth();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.amv_access_api.NonceAuth.serializeBinaryToWriter
    );
  }
  f = message.getIssuerUuid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional NonceAuth nonce_auth = 1;
 * @return {?proto.amv_access_api.NonceAuth}
 */
proto.amv_access_api.IssuerAuth.prototype.getNonceAuth = function() {
  return /** @type{?proto.amv_access_api.NonceAuth} */ (
    jspb.Message.getWrapperField(this, proto.amv_access_api.NonceAuth, 1));
};


/** @param {?proto.amv_access_api.NonceAuth|undefined} value */
proto.amv_access_api.IssuerAuth.prototype.setNonceAuth = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.amv_access_api.IssuerAuth.prototype.clearNonceAuth = function() {
  this.setNonceAuth(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.amv_access_api.IssuerAuth.prototype.hasNonceAuth = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string issuer_uuid = 2;
 * @return {string}
 */
proto.amv_access_api.IssuerAuth.prototype.getIssuerUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.amv_access_api.IssuerAuth.prototype.setIssuerUuid = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.amv_access_api.DeviceAuth = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.amv_access_api.DeviceAuth, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.amv_access_api.DeviceAuth.displayName = 'proto.amv_access_api.DeviceAuth';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.amv_access_api.DeviceAuth.prototype.toObject = function(opt_includeInstance) {
  return proto.amv_access_api.DeviceAuth.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.amv_access_api.DeviceAuth} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.DeviceAuth.toObject = function(includeInstance, msg) {
  var f, obj = {
    nonceAuth: (f = msg.getNonceAuth()) && proto.amv_access_api.NonceAuth.toObject(includeInstance, f),
    deviceSerialNumber: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.amv_access_api.DeviceAuth}
 */
proto.amv_access_api.DeviceAuth.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.amv_access_api.DeviceAuth;
  return proto.amv_access_api.DeviceAuth.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.amv_access_api.DeviceAuth} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.amv_access_api.DeviceAuth}
 */
proto.amv_access_api.DeviceAuth.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.amv_access_api.NonceAuth;
      reader.readMessage(value,proto.amv_access_api.NonceAuth.deserializeBinaryFromReader);
      msg.setNonceAuth(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceSerialNumber(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.amv_access_api.DeviceAuth.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.amv_access_api.DeviceAuth.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.amv_access_api.DeviceAuth} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.DeviceAuth.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNonceAuth();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.amv_access_api.NonceAuth.serializeBinaryToWriter
    );
  }
  f = message.getDeviceSerialNumber();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional NonceAuth nonce_auth = 1;
 * @return {?proto.amv_access_api.NonceAuth}
 */
proto.amv_access_api.DeviceAuth.prototype.getNonceAuth = function() {
  return /** @type{?proto.amv_access_api.NonceAuth} */ (
    jspb.Message.getWrapperField(this, proto.amv_access_api.NonceAuth, 1));
};


/** @param {?proto.amv_access_api.NonceAuth|undefined} value */
proto.amv_access_api.DeviceAuth.prototype.setNonceAuth = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.amv_access_api.DeviceAuth.prototype.clearNonceAuth = function() {
  this.setNonceAuth(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.amv_access_api.DeviceAuth.prototype.hasNonceAuth = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string device_serial_number = 2;
 * @return {string}
 */
proto.amv_access_api.DeviceAuth.prototype.getDeviceSerialNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.amv_access_api.DeviceAuth.prototype.setDeviceSerialNumber = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.amv_access_api);
