/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var access_api_auth_pb = require('./access_api_auth_pb.js');
goog.exportSymbol('proto.amv_access_api.CreateDeviceCertificateRequest', null, global);
goog.exportSymbol('proto.amv_access_api.CreateDeviceCertificateResponse', null, global);
goog.exportSymbol('proto.amv_access_api.DeviceCertificate', null, global);
goog.exportSymbol('proto.amv_access_api.DeviceCertificateResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.amv_access_api.CreateDeviceCertificateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.amv_access_api.CreateDeviceCertificateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.amv_access_api.CreateDeviceCertificateRequest.displayName = 'proto.amv_access_api.CreateDeviceCertificateRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.amv_access_api.CreateDeviceCertificateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.amv_access_api.CreateDeviceCertificateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.amv_access_api.CreateDeviceCertificateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.CreateDeviceCertificateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    devicePublicKey: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.amv_access_api.CreateDeviceCertificateRequest}
 */
proto.amv_access_api.CreateDeviceCertificateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.amv_access_api.CreateDeviceCertificateRequest;
  return proto.amv_access_api.CreateDeviceCertificateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.amv_access_api.CreateDeviceCertificateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.amv_access_api.CreateDeviceCertificateRequest}
 */
proto.amv_access_api.CreateDeviceCertificateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevicePublicKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.amv_access_api.CreateDeviceCertificateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.amv_access_api.CreateDeviceCertificateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.amv_access_api.CreateDeviceCertificateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.CreateDeviceCertificateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDevicePublicKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string device_public_key = 1;
 * @return {string}
 */
proto.amv_access_api.CreateDeviceCertificateRequest.prototype.getDevicePublicKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.amv_access_api.CreateDeviceCertificateRequest.prototype.setDevicePublicKey = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.amv_access_api.CreateDeviceCertificateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.amv_access_api.CreateDeviceCertificateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.amv_access_api.CreateDeviceCertificateResponse.displayName = 'proto.amv_access_api.CreateDeviceCertificateResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.amv_access_api.CreateDeviceCertificateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.amv_access_api.CreateDeviceCertificateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.amv_access_api.CreateDeviceCertificateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.CreateDeviceCertificateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    deviceCertificate: (f = msg.getDeviceCertificate()) && proto.amv_access_api.DeviceCertificate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.amv_access_api.CreateDeviceCertificateResponse}
 */
proto.amv_access_api.CreateDeviceCertificateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.amv_access_api.CreateDeviceCertificateResponse;
  return proto.amv_access_api.CreateDeviceCertificateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.amv_access_api.CreateDeviceCertificateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.amv_access_api.CreateDeviceCertificateResponse}
 */
proto.amv_access_api.CreateDeviceCertificateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.amv_access_api.DeviceCertificate;
      reader.readMessage(value,proto.amv_access_api.DeviceCertificate.deserializeBinaryFromReader);
      msg.setDeviceCertificate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.amv_access_api.CreateDeviceCertificateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.amv_access_api.CreateDeviceCertificateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.amv_access_api.CreateDeviceCertificateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.CreateDeviceCertificateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDeviceCertificate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.amv_access_api.DeviceCertificate.serializeBinaryToWriter
    );
  }
};


/**
 * optional DeviceCertificate device_certificate = 1;
 * @return {?proto.amv_access_api.DeviceCertificate}
 */
proto.amv_access_api.CreateDeviceCertificateResponse.prototype.getDeviceCertificate = function() {
  return /** @type{?proto.amv_access_api.DeviceCertificate} */ (
    jspb.Message.getWrapperField(this, proto.amv_access_api.DeviceCertificate, 1));
};


/** @param {?proto.amv_access_api.DeviceCertificate|undefined} value */
proto.amv_access_api.CreateDeviceCertificateResponse.prototype.setDeviceCertificate = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.amv_access_api.CreateDeviceCertificateResponse.prototype.clearDeviceCertificate = function() {
  this.setDeviceCertificate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.amv_access_api.CreateDeviceCertificateResponse.prototype.hasDeviceCertificate = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.amv_access_api.DeviceCertificate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.amv_access_api.DeviceCertificate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.amv_access_api.DeviceCertificate.displayName = 'proto.amv_access_api.DeviceCertificate';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.amv_access_api.DeviceCertificate.prototype.toObject = function(opt_includeInstance) {
  return proto.amv_access_api.DeviceCertificate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.amv_access_api.DeviceCertificate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.DeviceCertificate.toObject = function(includeInstance, msg) {
  var f, obj = {
    deviceCertificate: jspb.Message.getFieldWithDefault(msg, 1, ""),
    issuerPublicKey: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.amv_access_api.DeviceCertificate}
 */
proto.amv_access_api.DeviceCertificate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.amv_access_api.DeviceCertificate;
  return proto.amv_access_api.DeviceCertificate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.amv_access_api.DeviceCertificate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.amv_access_api.DeviceCertificate}
 */
proto.amv_access_api.DeviceCertificate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceCertificate(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIssuerPublicKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.amv_access_api.DeviceCertificate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.amv_access_api.DeviceCertificate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.amv_access_api.DeviceCertificate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.DeviceCertificate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDeviceCertificate();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIssuerPublicKey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string device_certificate = 1;
 * @return {string}
 */
proto.amv_access_api.DeviceCertificate.prototype.getDeviceCertificate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.amv_access_api.DeviceCertificate.prototype.setDeviceCertificate = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string issuer_public_key = 2;
 * @return {string}
 */
proto.amv_access_api.DeviceCertificate.prototype.getIssuerPublicKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.amv_access_api.DeviceCertificate.prototype.setIssuerPublicKey = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.amv_access_api.DeviceCertificateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.amv_access_api.DeviceCertificateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.amv_access_api.DeviceCertificateResponse.displayName = 'proto.amv_access_api.DeviceCertificateResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.amv_access_api.DeviceCertificateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.amv_access_api.DeviceCertificateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.amv_access_api.DeviceCertificateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.DeviceCertificateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    deviceCertificate: (f = msg.getDeviceCertificate()) && proto.amv_access_api.DeviceCertificate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.amv_access_api.DeviceCertificateResponse}
 */
proto.amv_access_api.DeviceCertificateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.amv_access_api.DeviceCertificateResponse;
  return proto.amv_access_api.DeviceCertificateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.amv_access_api.DeviceCertificateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.amv_access_api.DeviceCertificateResponse}
 */
proto.amv_access_api.DeviceCertificateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.amv_access_api.DeviceCertificate;
      reader.readMessage(value,proto.amv_access_api.DeviceCertificate.deserializeBinaryFromReader);
      msg.setDeviceCertificate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.amv_access_api.DeviceCertificateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.amv_access_api.DeviceCertificateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.amv_access_api.DeviceCertificateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amv_access_api.DeviceCertificateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDeviceCertificate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.amv_access_api.DeviceCertificate.serializeBinaryToWriter
    );
  }
};


/**
 * optional DeviceCertificate device_certificate = 1;
 * @return {?proto.amv_access_api.DeviceCertificate}
 */
proto.amv_access_api.DeviceCertificateResponse.prototype.getDeviceCertificate = function() {
  return /** @type{?proto.amv_access_api.DeviceCertificate} */ (
    jspb.Message.getWrapperField(this, proto.amv_access_api.DeviceCertificate, 1));
};


/** @param {?proto.amv_access_api.DeviceCertificate|undefined} value */
proto.amv_access_api.DeviceCertificateResponse.prototype.setDeviceCertificate = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.amv_access_api.DeviceCertificateResponse.prototype.clearDeviceCertificate = function() {
  this.setDeviceCertificate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.amv_access_api.DeviceCertificateResponse.prototype.hasDeviceCertificate = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.amv_access_api);
