// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access_api_auth.proto

package org.amv.access.grpc.auth;

public final class AccessAuthProto {
  private AccessAuthProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_NonceAuth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_NonceAuth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_IssuerAuth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_IssuerAuth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_DeviceAuth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_DeviceAuth_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025access_api_auth.proto\022\016amv_access_api\"" +
      "3\n\tNonceAuth\022\r\n\005nonce\030\001 \001(\t\022\027\n\017nonce_sig" +
      "nature\030\002 \001(\t\"P\n\nIssuerAuth\022-\n\nnonce_auth" +
      "\030\001 \001(\0132\031.amv_access_api.NonceAuth\022\023\n\013iss" +
      "uer_uuid\030\002 \001(\t\"Y\n\nDeviceAuth\022-\n\nnonce_au" +
      "th\030\001 \001(\0132\031.amv_access_api.NonceAuth\022\034\n\024d" +
      "evice_serial_number\030\002 \001(\tB-\n\030org.amv.acc" +
      "ess.grpc.authB\017AccessAuthProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_amv_access_api_NonceAuth_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_amv_access_api_NonceAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_NonceAuth_descriptor,
        new java.lang.String[] { "Nonce", "NonceSignature", });
    internal_static_amv_access_api_IssuerAuth_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_amv_access_api_IssuerAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_IssuerAuth_descriptor,
        new java.lang.String[] { "NonceAuth", "IssuerUuid", });
    internal_static_amv_access_api_DeviceAuth_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_amv_access_api_DeviceAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_DeviceAuth_descriptor,
        new java.lang.String[] { "NonceAuth", "DeviceSerialNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
