// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access_api_auth.proto

package org.amv.access.grpc.auth;

public interface NonceAuthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amv_access_api.NonceAuth)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nonce = 1;</code>
   */
  java.lang.String getNonce();
  /**
   * <code>string nonce = 1;</code>
   */
  com.google.protobuf.ByteString
      getNonceBytes();

  /**
   * <code>string nonce_signature = 2;</code>
   */
  java.lang.String getNonceSignature();
  /**
   * <code>string nonce_signature = 2;</code>
   */
  com.google.protobuf.ByteString
      getNonceSignatureBytes();
}
