// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package org.amv.access.grpc;

public interface AccessCertificateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amv_access_api.AccessCertificate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string device_access_certificate = 2;</code>
   */
  java.lang.String getDeviceAccessCertificate();
  /**
   * <code>string device_access_certificate = 2;</code>
   */
  com.google.protobuf.ByteString
      getDeviceAccessCertificateBytes();

  /**
   * <code>string vehicle_access_certificate = 3;</code>
   */
  java.lang.String getVehicleAccessCertificate();
  /**
   * <code>string vehicle_access_certificate = 3;</code>
   */
  com.google.protobuf.ByteString
      getVehicleAccessCertificateBytes();

  /**
   * <code>string name = 4;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
