// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access_api.proto

package org.amv.access.grpc;

/**
 * Protobuf type {@code amv_access_api.CreateVehicleRequest}
 */
public  final class CreateVehicleRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:amv_access_api.CreateVehicleRequest)
    CreateVehicleRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateVehicleRequest.newBuilder() to construct.
  private CreateVehicleRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateVehicleRequest() {
    name_ = "";
    description_ = "";
    publicKeyBase64_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateVehicleRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.amv.access.grpc.IssuerAuth.Builder subBuilder = null;
            if (issuerAuth_ != null) {
              subBuilder = issuerAuth_.toBuilder();
            }
            issuerAuth_ = input.readMessage(org.amv.access.grpc.IssuerAuth.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(issuerAuth_);
              issuerAuth_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            publicKeyBase64_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.amv.access.grpc.AccessApi.internal_static_amv_access_api_CreateVehicleRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.amv.access.grpc.AccessApi.internal_static_amv_access_api_CreateVehicleRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.amv.access.grpc.CreateVehicleRequest.class, org.amv.access.grpc.CreateVehicleRequest.Builder.class);
  }

  public static final int ISSUER_AUTH_FIELD_NUMBER = 1;
  private org.amv.access.grpc.IssuerAuth issuerAuth_;
  /**
   * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
   */
  public boolean hasIssuerAuth() {
    return issuerAuth_ != null;
  }
  /**
   * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
   */
  public org.amv.access.grpc.IssuerAuth getIssuerAuth() {
    return issuerAuth_ == null ? org.amv.access.grpc.IssuerAuth.getDefaultInstance() : issuerAuth_;
  }
  /**
   * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
   */
  public org.amv.access.grpc.IssuerAuthOrBuilder getIssuerAuthOrBuilder() {
    return getIssuerAuth();
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 3;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUBLIC_KEY_BASE64_FIELD_NUMBER = 4;
  private volatile java.lang.Object publicKeyBase64_;
  /**
   * <code>string public_key_base64 = 4;</code>
   */
  public java.lang.String getPublicKeyBase64() {
    java.lang.Object ref = publicKeyBase64_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      publicKeyBase64_ = s;
      return s;
    }
  }
  /**
   * <code>string public_key_base64 = 4;</code>
   */
  public com.google.protobuf.ByteString
      getPublicKeyBase64Bytes() {
    java.lang.Object ref = publicKeyBase64_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      publicKeyBase64_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (issuerAuth_ != null) {
      output.writeMessage(1, getIssuerAuth());
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    if (!getPublicKeyBase64Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, publicKeyBase64_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (issuerAuth_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getIssuerAuth());
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    if (!getPublicKeyBase64Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, publicKeyBase64_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.amv.access.grpc.CreateVehicleRequest)) {
      return super.equals(obj);
    }
    org.amv.access.grpc.CreateVehicleRequest other = (org.amv.access.grpc.CreateVehicleRequest) obj;

    boolean result = true;
    result = result && (hasIssuerAuth() == other.hasIssuerAuth());
    if (hasIssuerAuth()) {
      result = result && getIssuerAuth()
          .equals(other.getIssuerAuth());
    }
    result = result && getName()
        .equals(other.getName());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && getPublicKeyBase64()
        .equals(other.getPublicKeyBase64());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIssuerAuth()) {
      hash = (37 * hash) + ISSUER_AUTH_FIELD_NUMBER;
      hash = (53 * hash) + getIssuerAuth().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + PUBLIC_KEY_BASE64_FIELD_NUMBER;
    hash = (53 * hash) + getPublicKeyBase64().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.amv.access.grpc.CreateVehicleRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.amv.access.grpc.CreateVehicleRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.amv.access.grpc.CreateVehicleRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.amv.access.grpc.CreateVehicleRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.amv.access.grpc.CreateVehicleRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.amv.access.grpc.CreateVehicleRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.amv.access.grpc.CreateVehicleRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.amv.access.grpc.CreateVehicleRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.amv.access.grpc.CreateVehicleRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.amv.access.grpc.CreateVehicleRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.amv.access.grpc.CreateVehicleRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.amv.access.grpc.CreateVehicleRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.amv.access.grpc.CreateVehicleRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code amv_access_api.CreateVehicleRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:amv_access_api.CreateVehicleRequest)
      org.amv.access.grpc.CreateVehicleRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.amv.access.grpc.AccessApi.internal_static_amv_access_api_CreateVehicleRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.amv.access.grpc.AccessApi.internal_static_amv_access_api_CreateVehicleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.amv.access.grpc.CreateVehicleRequest.class, org.amv.access.grpc.CreateVehicleRequest.Builder.class);
    }

    // Construct using org.amv.access.grpc.CreateVehicleRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (issuerAuthBuilder_ == null) {
        issuerAuth_ = null;
      } else {
        issuerAuth_ = null;
        issuerAuthBuilder_ = null;
      }
      name_ = "";

      description_ = "";

      publicKeyBase64_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.amv.access.grpc.AccessApi.internal_static_amv_access_api_CreateVehicleRequest_descriptor;
    }

    public org.amv.access.grpc.CreateVehicleRequest getDefaultInstanceForType() {
      return org.amv.access.grpc.CreateVehicleRequest.getDefaultInstance();
    }

    public org.amv.access.grpc.CreateVehicleRequest build() {
      org.amv.access.grpc.CreateVehicleRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.amv.access.grpc.CreateVehicleRequest buildPartial() {
      org.amv.access.grpc.CreateVehicleRequest result = new org.amv.access.grpc.CreateVehicleRequest(this);
      if (issuerAuthBuilder_ == null) {
        result.issuerAuth_ = issuerAuth_;
      } else {
        result.issuerAuth_ = issuerAuthBuilder_.build();
      }
      result.name_ = name_;
      result.description_ = description_;
      result.publicKeyBase64_ = publicKeyBase64_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.amv.access.grpc.CreateVehicleRequest) {
        return mergeFrom((org.amv.access.grpc.CreateVehicleRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.amv.access.grpc.CreateVehicleRequest other) {
      if (other == org.amv.access.grpc.CreateVehicleRequest.getDefaultInstance()) return this;
      if (other.hasIssuerAuth()) {
        mergeIssuerAuth(other.getIssuerAuth());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getPublicKeyBase64().isEmpty()) {
        publicKeyBase64_ = other.publicKeyBase64_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.amv.access.grpc.CreateVehicleRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.amv.access.grpc.CreateVehicleRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.amv.access.grpc.IssuerAuth issuerAuth_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.amv.access.grpc.IssuerAuth, org.amv.access.grpc.IssuerAuth.Builder, org.amv.access.grpc.IssuerAuthOrBuilder> issuerAuthBuilder_;
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public boolean hasIssuerAuth() {
      return issuerAuthBuilder_ != null || issuerAuth_ != null;
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public org.amv.access.grpc.IssuerAuth getIssuerAuth() {
      if (issuerAuthBuilder_ == null) {
        return issuerAuth_ == null ? org.amv.access.grpc.IssuerAuth.getDefaultInstance() : issuerAuth_;
      } else {
        return issuerAuthBuilder_.getMessage();
      }
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public Builder setIssuerAuth(org.amv.access.grpc.IssuerAuth value) {
      if (issuerAuthBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        issuerAuth_ = value;
        onChanged();
      } else {
        issuerAuthBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public Builder setIssuerAuth(
        org.amv.access.grpc.IssuerAuth.Builder builderForValue) {
      if (issuerAuthBuilder_ == null) {
        issuerAuth_ = builderForValue.build();
        onChanged();
      } else {
        issuerAuthBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public Builder mergeIssuerAuth(org.amv.access.grpc.IssuerAuth value) {
      if (issuerAuthBuilder_ == null) {
        if (issuerAuth_ != null) {
          issuerAuth_ =
            org.amv.access.grpc.IssuerAuth.newBuilder(issuerAuth_).mergeFrom(value).buildPartial();
        } else {
          issuerAuth_ = value;
        }
        onChanged();
      } else {
        issuerAuthBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public Builder clearIssuerAuth() {
      if (issuerAuthBuilder_ == null) {
        issuerAuth_ = null;
        onChanged();
      } else {
        issuerAuth_ = null;
        issuerAuthBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public org.amv.access.grpc.IssuerAuth.Builder getIssuerAuthBuilder() {
      
      onChanged();
      return getIssuerAuthFieldBuilder().getBuilder();
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    public org.amv.access.grpc.IssuerAuthOrBuilder getIssuerAuthOrBuilder() {
      if (issuerAuthBuilder_ != null) {
        return issuerAuthBuilder_.getMessageOrBuilder();
      } else {
        return issuerAuth_ == null ?
            org.amv.access.grpc.IssuerAuth.getDefaultInstance() : issuerAuth_;
      }
    }
    /**
     * <code>.amv_access_api.IssuerAuth issuer_auth = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.amv.access.grpc.IssuerAuth, org.amv.access.grpc.IssuerAuth.Builder, org.amv.access.grpc.IssuerAuthOrBuilder> 
        getIssuerAuthFieldBuilder() {
      if (issuerAuthBuilder_ == null) {
        issuerAuthBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.amv.access.grpc.IssuerAuth, org.amv.access.grpc.IssuerAuth.Builder, org.amv.access.grpc.IssuerAuthOrBuilder>(
                getIssuerAuth(),
                getParentForChildren(),
                isClean());
        issuerAuth_ = null;
      }
      return issuerAuthBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object publicKeyBase64_ = "";
    /**
     * <code>string public_key_base64 = 4;</code>
     */
    public java.lang.String getPublicKeyBase64() {
      java.lang.Object ref = publicKeyBase64_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publicKeyBase64_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string public_key_base64 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPublicKeyBase64Bytes() {
      java.lang.Object ref = publicKeyBase64_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publicKeyBase64_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string public_key_base64 = 4;</code>
     */
    public Builder setPublicKeyBase64(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      publicKeyBase64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string public_key_base64 = 4;</code>
     */
    public Builder clearPublicKeyBase64() {
      
      publicKeyBase64_ = getDefaultInstance().getPublicKeyBase64();
      onChanged();
      return this;
    }
    /**
     * <code>string public_key_base64 = 4;</code>
     */
    public Builder setPublicKeyBase64Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      publicKeyBase64_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:amv_access_api.CreateVehicleRequest)
  }

  // @@protoc_insertion_point(class_scope:amv_access_api.CreateVehicleRequest)
  private static final org.amv.access.grpc.CreateVehicleRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.amv.access.grpc.CreateVehicleRequest();
  }

  public static org.amv.access.grpc.CreateVehicleRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateVehicleRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateVehicleRequest>() {
    public CreateVehicleRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateVehicleRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateVehicleRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateVehicleRequest> getParserForType() {
    return PARSER;
  }

  public org.amv.access.grpc.CreateVehicleRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

