// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package org.amv.access.grpc;

/**
 * Protobuf type {@code amv_access_api.CreateDeviceCertificateResponse}
 */
public  final class CreateDeviceCertificateResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:amv_access_api.CreateDeviceCertificateResponse)
    CreateDeviceCertificateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateDeviceCertificateResponse.newBuilder() to construct.
  private CreateDeviceCertificateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateDeviceCertificateResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateDeviceCertificateResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.amv.access.grpc.DeviceCertificate.Builder subBuilder = null;
            if (deviceCertificate_ != null) {
              subBuilder = deviceCertificate_.toBuilder();
            }
            deviceCertificate_ = input.readMessage(org.amv.access.grpc.DeviceCertificate.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(deviceCertificate_);
              deviceCertificate_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.amv.access.grpc.RouteGuideProto.internal_static_amv_access_api_CreateDeviceCertificateResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.amv.access.grpc.RouteGuideProto.internal_static_amv_access_api_CreateDeviceCertificateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.amv.access.grpc.CreateDeviceCertificateResponse.class, org.amv.access.grpc.CreateDeviceCertificateResponse.Builder.class);
  }

  public static final int DEVICE_CERTIFICATE_FIELD_NUMBER = 1;
  private org.amv.access.grpc.DeviceCertificate deviceCertificate_;
  /**
   * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
   */
  public boolean hasDeviceCertificate() {
    return deviceCertificate_ != null;
  }
  /**
   * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
   */
  public org.amv.access.grpc.DeviceCertificate getDeviceCertificate() {
    return deviceCertificate_ == null ? org.amv.access.grpc.DeviceCertificate.getDefaultInstance() : deviceCertificate_;
  }
  /**
   * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
   */
  public org.amv.access.grpc.DeviceCertificateOrBuilder getDeviceCertificateOrBuilder() {
    return getDeviceCertificate();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (deviceCertificate_ != null) {
      output.writeMessage(1, getDeviceCertificate());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (deviceCertificate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDeviceCertificate());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.amv.access.grpc.CreateDeviceCertificateResponse)) {
      return super.equals(obj);
    }
    org.amv.access.grpc.CreateDeviceCertificateResponse other = (org.amv.access.grpc.CreateDeviceCertificateResponse) obj;

    boolean result = true;
    result = result && (hasDeviceCertificate() == other.hasDeviceCertificate());
    if (hasDeviceCertificate()) {
      result = result && getDeviceCertificate()
          .equals(other.getDeviceCertificate());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDeviceCertificate()) {
      hash = (37 * hash) + DEVICE_CERTIFICATE_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceCertificate().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.amv.access.grpc.CreateDeviceCertificateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.amv.access.grpc.CreateDeviceCertificateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.amv.access.grpc.CreateDeviceCertificateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.amv.access.grpc.CreateDeviceCertificateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.amv.access.grpc.CreateDeviceCertificateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.amv.access.grpc.CreateDeviceCertificateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.amv.access.grpc.CreateDeviceCertificateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.amv.access.grpc.CreateDeviceCertificateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.amv.access.grpc.CreateDeviceCertificateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.amv.access.grpc.CreateDeviceCertificateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.amv.access.grpc.CreateDeviceCertificateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.amv.access.grpc.CreateDeviceCertificateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.amv.access.grpc.CreateDeviceCertificateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code amv_access_api.CreateDeviceCertificateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:amv_access_api.CreateDeviceCertificateResponse)
      org.amv.access.grpc.CreateDeviceCertificateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.amv.access.grpc.RouteGuideProto.internal_static_amv_access_api_CreateDeviceCertificateResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.amv.access.grpc.RouteGuideProto.internal_static_amv_access_api_CreateDeviceCertificateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.amv.access.grpc.CreateDeviceCertificateResponse.class, org.amv.access.grpc.CreateDeviceCertificateResponse.Builder.class);
    }

    // Construct using org.amv.access.grpc.CreateDeviceCertificateResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (deviceCertificateBuilder_ == null) {
        deviceCertificate_ = null;
      } else {
        deviceCertificate_ = null;
        deviceCertificateBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.amv.access.grpc.RouteGuideProto.internal_static_amv_access_api_CreateDeviceCertificateResponse_descriptor;
    }

    public org.amv.access.grpc.CreateDeviceCertificateResponse getDefaultInstanceForType() {
      return org.amv.access.grpc.CreateDeviceCertificateResponse.getDefaultInstance();
    }

    public org.amv.access.grpc.CreateDeviceCertificateResponse build() {
      org.amv.access.grpc.CreateDeviceCertificateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.amv.access.grpc.CreateDeviceCertificateResponse buildPartial() {
      org.amv.access.grpc.CreateDeviceCertificateResponse result = new org.amv.access.grpc.CreateDeviceCertificateResponse(this);
      if (deviceCertificateBuilder_ == null) {
        result.deviceCertificate_ = deviceCertificate_;
      } else {
        result.deviceCertificate_ = deviceCertificateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.amv.access.grpc.CreateDeviceCertificateResponse) {
        return mergeFrom((org.amv.access.grpc.CreateDeviceCertificateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.amv.access.grpc.CreateDeviceCertificateResponse other) {
      if (other == org.amv.access.grpc.CreateDeviceCertificateResponse.getDefaultInstance()) return this;
      if (other.hasDeviceCertificate()) {
        mergeDeviceCertificate(other.getDeviceCertificate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.amv.access.grpc.CreateDeviceCertificateResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.amv.access.grpc.CreateDeviceCertificateResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.amv.access.grpc.DeviceCertificate deviceCertificate_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.amv.access.grpc.DeviceCertificate, org.amv.access.grpc.DeviceCertificate.Builder, org.amv.access.grpc.DeviceCertificateOrBuilder> deviceCertificateBuilder_;
    /**
     * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
     */
    public boolean hasDeviceCertificate() {
      return deviceCertificateBuilder_ != null || deviceCertificate_ != null;
    }
    /**
     * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
     */
    public org.amv.access.grpc.DeviceCertificate getDeviceCertificate() {
      if (deviceCertificateBuilder_ == null) {
        return deviceCertificate_ == null ? org.amv.access.grpc.DeviceCertificate.getDefaultInstance() : deviceCertificate_;
      } else {
        return deviceCertificateBuilder_.getMessage();
      }
    }
    /**
     * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
     */
    public Builder setDeviceCertificate(org.amv.access.grpc.DeviceCertificate value) {
      if (deviceCertificateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deviceCertificate_ = value;
        onChanged();
      } else {
        deviceCertificateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
     */
    public Builder setDeviceCertificate(
        org.amv.access.grpc.DeviceCertificate.Builder builderForValue) {
      if (deviceCertificateBuilder_ == null) {
        deviceCertificate_ = builderForValue.build();
        onChanged();
      } else {
        deviceCertificateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
     */
    public Builder mergeDeviceCertificate(org.amv.access.grpc.DeviceCertificate value) {
      if (deviceCertificateBuilder_ == null) {
        if (deviceCertificate_ != null) {
          deviceCertificate_ =
            org.amv.access.grpc.DeviceCertificate.newBuilder(deviceCertificate_).mergeFrom(value).buildPartial();
        } else {
          deviceCertificate_ = value;
        }
        onChanged();
      } else {
        deviceCertificateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
     */
    public Builder clearDeviceCertificate() {
      if (deviceCertificateBuilder_ == null) {
        deviceCertificate_ = null;
        onChanged();
      } else {
        deviceCertificate_ = null;
        deviceCertificateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
     */
    public org.amv.access.grpc.DeviceCertificate.Builder getDeviceCertificateBuilder() {
      
      onChanged();
      return getDeviceCertificateFieldBuilder().getBuilder();
    }
    /**
     * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
     */
    public org.amv.access.grpc.DeviceCertificateOrBuilder getDeviceCertificateOrBuilder() {
      if (deviceCertificateBuilder_ != null) {
        return deviceCertificateBuilder_.getMessageOrBuilder();
      } else {
        return deviceCertificate_ == null ?
            org.amv.access.grpc.DeviceCertificate.getDefaultInstance() : deviceCertificate_;
      }
    }
    /**
     * <code>.amv_access_api.DeviceCertificate device_certificate = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.amv.access.grpc.DeviceCertificate, org.amv.access.grpc.DeviceCertificate.Builder, org.amv.access.grpc.DeviceCertificateOrBuilder> 
        getDeviceCertificateFieldBuilder() {
      if (deviceCertificateBuilder_ == null) {
        deviceCertificateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.amv.access.grpc.DeviceCertificate, org.amv.access.grpc.DeviceCertificate.Builder, org.amv.access.grpc.DeviceCertificateOrBuilder>(
                getDeviceCertificate(),
                getParentForChildren(),
                isClean());
        deviceCertificate_ = null;
      }
      return deviceCertificateBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:amv_access_api.CreateDeviceCertificateResponse)
  }

  // @@protoc_insertion_point(class_scope:amv_access_api.CreateDeviceCertificateResponse)
  private static final org.amv.access.grpc.CreateDeviceCertificateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.amv.access.grpc.CreateDeviceCertificateResponse();
  }

  public static org.amv.access.grpc.CreateDeviceCertificateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateDeviceCertificateResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateDeviceCertificateResponse>() {
    public CreateDeviceCertificateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateDeviceCertificateResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateDeviceCertificateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateDeviceCertificateResponse> getParserForType() {
    return PARSER;
  }

  public org.amv.access.grpc.CreateDeviceCertificateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

