// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package org.amv.access.grpc;

public interface DeviceCertificateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amv_access_api.DeviceCertificate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_certificate = 1;</code>
   */
  java.lang.String getDeviceCertificate();
  /**
   * <code>string device_certificate = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceCertificateBytes();

  /**
   * <code>string issuer_public_key = 2;</code>
   */
  java.lang.String getIssuerPublicKey();
  /**
   * <code>string issuer_public_key = 2;</code>
   */
  com.google.protobuf.ByteString
      getIssuerPublicKeyBytes();
}
