// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package org.amv.access.grpc;

public interface ErrorInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amv_access_api.ErrorInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string source = 2;</code>
   */
  java.lang.String getSource();
  /**
   * <code>string source = 2;</code>
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>string detail = 3;</code>
   */
  java.lang.String getDetail();
  /**
   * <code>string detail = 3;</code>
   */
  com.google.protobuf.ByteString
      getDetailBytes();
}
