// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package org.amv.access.grpc;

public interface FeatureDatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amv_access_api.FeatureDatabase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .amv_access_api.Feature feature = 1;</code>
   */
  java.util.List<org.amv.access.grpc.Feature> 
      getFeatureList();
  /**
   * <code>repeated .amv_access_api.Feature feature = 1;</code>
   */
  org.amv.access.grpc.Feature getFeature(int index);
  /**
   * <code>repeated .amv_access_api.Feature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .amv_access_api.Feature feature = 1;</code>
   */
  java.util.List<? extends org.amv.access.grpc.FeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .amv_access_api.Feature feature = 1;</code>
   */
  org.amv.access.grpc.FeatureOrBuilder getFeatureOrBuilder(
      int index);
}
