// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package org.amv.access.grpc;

public interface RectangleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:amv_access_api.Rectangle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.amv_access_api.Point lo = 1;</code>
   */
  boolean hasLo();
  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.amv_access_api.Point lo = 1;</code>
   */
  org.amv.access.grpc.Point getLo();
  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.amv_access_api.Point lo = 1;</code>
   */
  org.amv.access.grpc.PointOrBuilder getLoOrBuilder();

  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.amv_access_api.Point hi = 2;</code>
   */
  boolean hasHi();
  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.amv_access_api.Point hi = 2;</code>
   */
  org.amv.access.grpc.Point getHi();
  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.amv_access_api.Point hi = 2;</code>
   */
  org.amv.access.grpc.PointOrBuilder getHiOrBuilder();
}
