// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package org.amv.access.grpc;

public final class RouteGuideProto {
  private RouteGuideProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_ErrorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_ErrorInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_ErrorInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_NonceAuth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_NonceAuth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_IssuerAuth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_IssuerAuth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_DeviceAuth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_DeviceAuth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_AccessCertificate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_AccessCertificate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_GetAccessCertificatesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_GetAccessCertificatesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_CreateAccessCertificateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_CreateAccessCertificateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_CreateAccessCertificateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_CreateAccessCertificateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_UpdateAccessCertificateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_UpdateAccessCertificateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_AccessCertificateSigningRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_AccessCertificateSigningRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_CreateDeviceCertificateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_CreateDeviceCertificateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_CreateDeviceCertificateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_CreateDeviceCertificateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_DeviceCertificate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_DeviceCertificate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_DeviceCertificateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_DeviceCertificateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_Point_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_Rectangle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_Rectangle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_Feature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_Feature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_FeatureDatabase_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_FeatureDatabase_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_RouteNote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_RouteNote_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_amv_access_api_RouteSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_amv_access_api_RouteSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021route_guide.proto\022\016amv_access_api\":\n\rE" +
      "rrorResponse\022)\n\006errors\030\001 \003(\0132\031.amv_acces" +
      "s_api.ErrorInfo\":\n\tErrorInfo\022\r\n\005title\030\001 " +
      "\001(\t\022\016\n\006source\030\002 \001(\t\022\016\n\006detail\030\003 \001(\t\"0\n\tN" +
      "onceAuth\022\r\n\005nonce\030\001 \001(\t\022\024\n\014signed_nonce\030" +
      "\002 \001(\t\"P\n\nIssuerAuth\022-\n\nnonce_auth\030\001 \001(\0132" +
      "\031.amv_access_api.NonceAuth\022\023\n\013issuer_uui" +
      "d\030\002 \001(\t\"Y\n\nDeviceAuth\022-\n\nnonce_auth\030\001 \001(" +
      "\0132\031.amv_access_api.NonceAuth\022\034\n\024device_s" +
      "erial_number\030\002 \001(\t\"t\n\021AccessCertificate\022" +
      "\n\n\002id\030\001 \001(\t\022!\n\031device_access_certificate" +
      "\030\002 \001(\t\022\"\n\032vehicle_access_certificate\030\003 \001" +
      "(\t\022\014\n\004name\030\004 \001(\t\"_\n\035GetAccessCertificate" +
      "sResponse\022>\n\023access_certificates\030\001 \003(\0132!" +
      ".amv_access_api.AccessCertificate\"\233\001\n\036Cr" +
      "eateAccessCertificateRequest\022\016\n\006app_id\030\001" +
      " \001(\t\022\034\n\024device_serial_number\030\002 \001(\t\022\035\n\025ve" +
      "hicle_serial_number\030\003 \001(\t\022\026\n\016validity_st" +
      "art\030\004 \001(\003\022\024\n\014validity_end\030\005 \001(\003\"~\n\037Creat" +
      "eAccessCertificateResponse\022[\n\"access_cer" +
      "tificate_signing_request\030\001 \001(\0132/.amv_acc" +
      "ess_api.AccessCertificateSigningRequest\"" +
      "\354\001\n\036UpdateAccessCertificateRequest\0223\n+ve" +
      "hicle_access_certificate_signature_base6" +
      "4\030\001 \001(\t\0220\n(signed_vehicle_access_certifi" +
      "cate_base64\030\002 \001(\t\0222\n*device_access_certi" +
      "ficate_signature_base64\030\003 \001(\t\022/\n\'signed_" +
      "device_access_certificate_base64\030\004 \001(\t\"t" +
      "\n\037AccessCertificateSigningRequest\022\n\n\002id\030" +
      "\001 \001(\t\022!\n\031device_access_certificate\030\002 \001(\t" +
      "\022\"\n\032vehicle_access_certificate\030\003 \001(\t\";\n\036" +
      "CreateDeviceCertificateRequest\022\031\n\021device" +
      "_public_key\030\001 \001(\t\"`\n\037CreateDeviceCertifi" +
      "cateResponse\022=\n\022device_certificate\030\001 \001(\013" +
      "2!.amv_access_api.DeviceCertificate\"J\n\021D" +
      "eviceCertificate\022\032\n\022device_certificate\030\001" +
      " \001(\t\022\031\n\021issuer_public_key\030\002 \001(\t\"Z\n\031Devic" +
      "eCertificateResponse\022=\n\022device_certifica" +
      "te\030\001 \001(\0132!.amv_access_api.DeviceCertific" +
      "ate\",\n\005Point\022\020\n\010latitude\030\001 \001(\005\022\021\n\tlongit" +
      "ude\030\002 \001(\005\"Q\n\tRectangle\022!\n\002lo\030\001 \001(\0132\025.amv" +
      "_access_api.Point\022!\n\002hi\030\002 \001(\0132\025.amv_acce" +
      "ss_api.Point\"@\n\007Feature\022\014\n\004name\030\001 \001(\t\022\'\n" +
      "\010location\030\002 \001(\0132\025.amv_access_api.Point\";" +
      "\n\017FeatureDatabase\022(\n\007feature\030\001 \003(\0132\027.amv" +
      "_access_api.Feature\"E\n\tRouteNote\022\'\n\010loca" +
      "tion\030\001 \001(\0132\025.amv_access_api.Point\022\017\n\007mes" +
      "sage\030\002 \001(\t\"b\n\014RouteSummary\022\023\n\013point_coun" +
      "t\030\001 \001(\005\022\025\n\rfeature_count\030\002 \001(\005\022\020\n\010distan" +
      "ce\030\003 \001(\005\022\024\n\014elapsed_time\030\004 \001(\0052\245\002\n\nRoute" +
      "Guide\022>\n\nGetFeature\022\025.amv_access_api.Poi" +
      "nt\032\027.amv_access_api.Feature\"\000\022F\n\014ListFea" +
      "tures\022\031.amv_access_api.Rectangle\032\027.amv_a" +
      "ccess_api.Feature\"\0000\001\022F\n\013RecordRoute\022\025.a" +
      "mv_access_api.Point\032\034.amv_access_api.Rou" +
      "teSummary\"\000(\001\022G\n\tRouteChat\022\031.amv_access_" +
      "api.RouteNote\032\031.amv_access_api.RouteNote" +
      "\"\000(\0010\001B.\n\023org.amv.access.grpcB\017RouteGuid" +
      "eProtoP\001\242\002\003RTGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_amv_access_api_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_amv_access_api_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_ErrorResponse_descriptor,
        new java.lang.String[] { "Errors", });
    internal_static_amv_access_api_ErrorInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_amv_access_api_ErrorInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_ErrorInfo_descriptor,
        new java.lang.String[] { "Title", "Source", "Detail", });
    internal_static_amv_access_api_NonceAuth_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_amv_access_api_NonceAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_NonceAuth_descriptor,
        new java.lang.String[] { "Nonce", "SignedNonce", });
    internal_static_amv_access_api_IssuerAuth_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_amv_access_api_IssuerAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_IssuerAuth_descriptor,
        new java.lang.String[] { "NonceAuth", "IssuerUuid", });
    internal_static_amv_access_api_DeviceAuth_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_amv_access_api_DeviceAuth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_DeviceAuth_descriptor,
        new java.lang.String[] { "NonceAuth", "DeviceSerialNumber", });
    internal_static_amv_access_api_AccessCertificate_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_amv_access_api_AccessCertificate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_AccessCertificate_descriptor,
        new java.lang.String[] { "Id", "DeviceAccessCertificate", "VehicleAccessCertificate", "Name", });
    internal_static_amv_access_api_GetAccessCertificatesResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_amv_access_api_GetAccessCertificatesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_GetAccessCertificatesResponse_descriptor,
        new java.lang.String[] { "AccessCertificates", });
    internal_static_amv_access_api_CreateAccessCertificateRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_amv_access_api_CreateAccessCertificateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_CreateAccessCertificateRequest_descriptor,
        new java.lang.String[] { "AppId", "DeviceSerialNumber", "VehicleSerialNumber", "ValidityStart", "ValidityEnd", });
    internal_static_amv_access_api_CreateAccessCertificateResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_amv_access_api_CreateAccessCertificateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_CreateAccessCertificateResponse_descriptor,
        new java.lang.String[] { "AccessCertificateSigningRequest", });
    internal_static_amv_access_api_UpdateAccessCertificateRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_amv_access_api_UpdateAccessCertificateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_UpdateAccessCertificateRequest_descriptor,
        new java.lang.String[] { "VehicleAccessCertificateSignatureBase64", "SignedVehicleAccessCertificateBase64", "DeviceAccessCertificateSignatureBase64", "SignedDeviceAccessCertificateBase64", });
    internal_static_amv_access_api_AccessCertificateSigningRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_amv_access_api_AccessCertificateSigningRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_AccessCertificateSigningRequest_descriptor,
        new java.lang.String[] { "Id", "DeviceAccessCertificate", "VehicleAccessCertificate", });
    internal_static_amv_access_api_CreateDeviceCertificateRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_amv_access_api_CreateDeviceCertificateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_CreateDeviceCertificateRequest_descriptor,
        new java.lang.String[] { "DevicePublicKey", });
    internal_static_amv_access_api_CreateDeviceCertificateResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_amv_access_api_CreateDeviceCertificateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_CreateDeviceCertificateResponse_descriptor,
        new java.lang.String[] { "DeviceCertificate", });
    internal_static_amv_access_api_DeviceCertificate_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_amv_access_api_DeviceCertificate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_DeviceCertificate_descriptor,
        new java.lang.String[] { "DeviceCertificate", "IssuerPublicKey", });
    internal_static_amv_access_api_DeviceCertificateResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_amv_access_api_DeviceCertificateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_DeviceCertificateResponse_descriptor,
        new java.lang.String[] { "DeviceCertificate", });
    internal_static_amv_access_api_Point_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_amv_access_api_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_Point_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_amv_access_api_Rectangle_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_amv_access_api_Rectangle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_Rectangle_descriptor,
        new java.lang.String[] { "Lo", "Hi", });
    internal_static_amv_access_api_Feature_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_amv_access_api_Feature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_Feature_descriptor,
        new java.lang.String[] { "Name", "Location", });
    internal_static_amv_access_api_FeatureDatabase_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_amv_access_api_FeatureDatabase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_FeatureDatabase_descriptor,
        new java.lang.String[] { "Feature", });
    internal_static_amv_access_api_RouteNote_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_amv_access_api_RouteNote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_RouteNote_descriptor,
        new java.lang.String[] { "Location", "Message", });
    internal_static_amv_access_api_RouteSummary_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_amv_access_api_RouteSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_amv_access_api_RouteSummary_descriptor,
        new java.lang.String[] { "PointCount", "FeatureCount", "Distance", "ElapsedTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
